name: CI/CD Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  test-and-deploy-dev:
    runs-on: ubuntu-latest

    env:
      APP_AWS_REGION: ap-northeast-1
      TABLE_NAME: sdvx_room_dev
      MAX_CONNECTIONS: "10"
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest --disable-warnings

      - name: Configure AWS Credentials (DEV)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::219930336567:role/github-actions-sdvx-deploy-dev-role
          role-session-name: github-deploy-sdvx-dev
          aws-region: ap-northeast-1

      - name: Deploy to AWS (Chalice Dev)
        run: chalice deploy --stage dev
